#!/bin/bash


website=alenalic.nl


echo "Starting installation"


echo "Updating system==============================="
sudo apt -y update
sudo apt -y upgrade
echo "System updated================================"

echo "Installing base dependencies=================="
sudo apt -y install supervisor nginx
echo "Base dependencies installed==================="


echo "Installing SSL certificate===================="
sudo apt install -y software-properties-common
sudo add-apt-repository -y universe
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt install -y certbot python-certbot-nginx
sudo certbot certonly --nginx $website
echo "Installing SSL certificate complete==========="


echo "Configuring Nginx============================="
if test -f "/etc/nginx/conf.d/default" 
then
sudo rm /etc/nginx/conf.d/default
fi

sudo -E bash -c 'cat > /etc/nginx/conf.d/$website.conf' << EOL
server {

	listen 443 ssl http2 default_server;
	server_name $website;

    root $HOME/Portfolio/dist;
    index index.html;
	
	location / {
		try_files \$uri \$uri/ =404;
	}

    access_log /var/log/$website.access.log;
    error_log /var/log/$website.error.log;

    ssl_certificate /etc/letsencrypt/live/$website/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$website/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

}
server {
    server_name $website;
    return 301 https://\$host\$request_uri;
}
EOL
echo "Configuring Nginx complete===================="


echo "Configuring firewall=========================="
sudo apt -y install ufw
sudo ufw allow http
sudo ufw allow https
sudo ufw allow ssh
sudo ufw --force enable
echo "Configuring firewall complete================="


echo "Website setup complete========================"
echo "Continue by running 'scripts/postfix'========="